import { Inter } from "next/font/google";
import "./globals.css";
import SProvider from "@/components/sessionProvider/sessionProvider";
import MainHeader from "@components/MainHeader/MainHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="cmyk">
      <body className={inter.className}>
        <SProvider>
          <main>{children}</main>
        </SProvider>
      </body>
    </html>
  );
}
